[package]
name = "sui-oracle"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
One = { git = "https://github.com/one-chain-labs/onechain.git", subdir = "crates/sui-framework/packages/one-framework", rev = "main" }

[addresses]
oracle = "0x0"
one = "0x2"
