# Stable configurations
edition = "2021"
max_width = 121
merge_derives = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true

# Nightly configurations
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
overflow_delimited_expr = true
reorder_impl_items = true
style_edition = "2021"
