name: Documentation

on:
  push:
    branches: [ main, extensions ]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]


jobs:
  diff:
    runs-on: [ubuntu-latest]
    outputs:
      isDoc: ${{ steps.diff.outputs.isDoc }}
      isOldDoc: ${{ steps.diff.outputs.isOldDoc }}
      isExamples: ${{ steps.diff.outputs.isExamples }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # Pin v5.0.0
      - name: Detect Changes
        uses: './.github/actions/diffs'
        id: diff

  examples:
    name: Notify Slack if examples directory changed
    needs: diff
    if: needs.diff.outputs.isExamples == 'true'
    runs-on: [ubuntu-latest]
    
    steps:
      - name: Notify Slack of Examples Changes
        uses: slackapi/slack-github-action@37ebaef184d7626c5f204ab8d3baff4262dd30f0 # pin@v1.27.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: 'tech-docs'
          slack-message: |
            An open PR modifies files in the `examples/` directory.
            Please review it: <https://github.com/${{ github.repository }}/pull/${{ github.event.number }}|PR${{ github.event.number }}>
  
  spelling:
    name: Lint documentation
    needs: diff
    if: needs.diff.outputs.isDoc == 'true'
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # Pin v5.0.0
      - name: Spell Check Docs
        uses: crate-ci/typos@v1.16.11
        with:
          files: ./docs/content
