name: Split Cluster Check
on: 
  pull_request:
jobs:
  validate-mainnet:
    runs-on: ubuntu-ghcloud
    steps:
      - name: checkout code repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # Pin v5.0.0
        with:
          fetch-depth: 0
      - name: Run split cluster check script
        id: mn-split-cluster-check
        run: | 
            SUI_PROTOCOL_CONFIG_CHAIN_OVERRIDE=mainnet \
            scripts/compatibility/split-cluster-check.sh origin/mainnet ${{ github.sha }}

  validate-testnet:
    runs-on: ubuntu-ghcloud
    steps:
      - name: checkout code repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # Pin v5.0.0
        with:
          fetch-depth: 0
      - name: Run split cluster check script
        id: tn-split-cluster-check
        run: | 
            SUI_PROTOCOL_CONFIG_CHAIN_OVERRIDE=testnet \
            scripts/compatibility/split-cluster-check.sh origin/testnet ${{ github.sha }}
